In [1]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import linalg

## Уровень 0
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [2]:
A = np.diag([1, -1]) #Диагональная, ортогональная, но не единичная
print(A)
np.linalg.matrix_rank(A)

[[ 1  0]
 [ 0 -1]]


2

In [3]:
AT = np.transpose(A)
np.dot(A, AT)

array([[1, 0],
       [0, 1]])

In [4]:
B = np.triu([[1,0,0],[4,1,0],[-1,-1,1]], 0)#диагональная как частный случай треугольной матрицы
print(B)
np.linalg.matrix_rank(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


3

In [5]:
BT = np.transpose(B)
np.dot(B, BT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
D = np.array([[5, 3], [3, 2]]) #Матрица, у которой определитель = 1, и все элементы не равны 0
det = np.linalg.det(D)
print(D)
print(det)
np.linalg.matrix_rank(D)

[[5 3]
 [3 2]]
1.0000000000000009


2

* Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])

In [21]:
m = np.array([[2, 2], [1, 3]])
print(m)
w, v = np.linalg.eig(m)

[[2 2]
 [1 3]]


In [22]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


## Уровень 1
Найдите спектральное разложение матрицы:

m_ = np.array([[1, 2],
              [2,3]])

In [23]:
m_ = np.array([[1, 2],[2,3]])
m_

array([[1, 2],
       [2, 3]])

In [24]:
a, U = linalg.eig(m_)
print('Eigenvalues:')
print(np.array(a, dtype=float))
print('\nEigenvectors:')
print(U)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


<ipython-input-24-384bfc1fa08a>:3: ComplexWarning: Casting complex values to real discards the imaginary part
  print(np.array(a, dtype=float))


In [25]:
np.array(U.dot(np.diag(a)).dot(U.T), dtype=float)#m_= U*D*UT

<ipython-input-25-3a55e9d5af13>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  np.array(U.dot(np.diag(a)).dot(U.T), dtype=float)


array([[1., 2.],
       [2., 3.]])